### PR TITLE
Remaining tidal features

### PR DESCRIPTION
**Pull request by unlessgames**
So this is not quite ready to be merged yet, but I open this request for discussion and report.

### Done

* repeats can be notated using `a ! ! !`
* `-` works as an alias for `~` rests like `a - - -`
* elongation using `a@2 b`
* `! @ ?` can be used without argument, defaults are `2 2 0.5` like in tidal
* polymeters now support the `{a b c, d e f g}` form like in tidal
* range expressions as `0..10` (only integers are supported)
* split shorthand for subdivisions like `a b . c d` -> `[a b] [c d]`
* cleaned up some excessive branching in the code using combinators
* applied the fix from #18 

Generating events is now almost pure (sans rng)!
* removed all internal state from steps
* output can be queried at arbitrary spans like cycles (0-2.5) and so on
* these made it possible to implement `/` expressions
* and floats for both `*` and `/` like `[a b c]*1.5` etc.
* interestingly, it turns out polymeters are just `*` expressions with `measure / length` on the right side :)

### TODOs

- [ ] Support patterns on the right side of `* / %`. This should be doable now that all of these use the same functionality and we can query any cycle iteration needed. 
- [ ] Support patterns on the right side of euclidean expressions, maybe not a high priority but it's possible in tidal

With these this tidal mini implementation will be pretty much complete (except for chord notation).

- [ ] The usage of RNG should be modified so that it gets seeded/sampled with the iteration count (on top of the user seed) to ensure that the same cycle will always produce the same output. I haven't looked into how the RNG we are using works, so I'd appreciate any input on this.
- [x] Parsing of sections, stacks and splits is a bit confusing in the code, this could be cleaned up.
- [ ] There might be some parts where we can optimize
- [ ] Maybe look into #9 

Anything else I'm forgetting?

### CODE REVIEW

**Comment by emuell** [comment]
Nice. That's quite a pack of features. Let me know when you are ready, I can then help with testing...

> With these this tidal mini implementation will be pretty much complete (except for chord notation).

I think we can/should evaluate chords in the CycleEventIter and not in the Cycle.
 
In the ["map" feature](https://github.com/emuell/afseq/tree/feature/cycle-mapping) I'm currently working on, it should later be possible to replace any identifiers with chords too, so there's no need to parse the chords via the PEG. 
 
> The usage of RNG should be modified so that it gets seeded/sampled with the iteration count (on top of the user seed)

Why is this necessary? As long as "generate" is not called in random order, it should give the same results for a seed anyway - without reseeding it with each new generate step?

**Comment by unlessgames** [comment]
> Why is this necessary? As long as "generate" is not called in random order, it should give the same results for a seed anyway - without reseeding it with each new generate step?

Generate might not be called in random order from the outside but for inner patterns it will be. Since divided groups need to output in a way as if  there were multiple patterns running alongside each other at different speeds. This is implemented in a way that a sub pattern is queried for output at half the speed for example, which results in querying the same inner iteration twice over two "outer" iterations.

For example `[a b]/2 c` needs to result in 
* `a c` in the first cycle, here `[a b]` is queried with span `0 -> 1/2` 
* `b c` in the second cycle, here `[a b]` was queried using span `1/2 -> 1`

There might be other cases where the RNG having its own global state is a problem but a simple one would be dividing a choice group.

`[[a b] | [c d]]/2`

Here tidal will output a single event per cycle, but `b` will always follow `a` and `d` will always follow `c` since cycles are queried in whole and their randomness is a pure function of the iteration count of the (sub)cycle and the seed.

**Comment by emuell** [comment]
I see. The probably easiert way to realize this might be using a  `seed: Option<u64>` instead of a `seed: Option<[u8; 32]>` which then can be easily manipulated or reseeded via https://docs.rs/rand_core/latest/rand_core/trait.SeedableRng.html#method.seed_from_u64

Actually makes sense to use u64 seeds anyway, as the original seed values comes from lua's `math.randomeseed()` which i've overridden here: 

https://github.com/emuell/afseq/blob/5db012c1d2f815510b3722b0da3fdf3246ca7fc5/src/bindings.rs#L394

But let's take care of this later in a separate PR? I'd then change the seed to u64 everywhere else too.

**Comment by unlessgames** [comment]
Okay, I guess you could give this a test and review then merge. The remaining features can be added later as well. This PR might be large enough already.

**Comment by emuell** [comment]
I can't diff or review the changes because there are too many changes. Let's break things down into smaller steps in the future.

But I've reviewed the tests and done a bit of testing with some expressions in scripts. Works great!

Would be great if you could do some final clean up and auto-format cycle.rs. I like working with auto-formatting in Rust on save. The Rust format is well defined, so one less thing to worry about when writing/modifying code.

Also, `use fraction::ToPrimitive;` should be at the top of the file. Or inside the function where it's used.

The docs mentioning the cycle impl restrictions in cycle.lua should also be updated.

---

The code is also getting harder and harder to read. Especially the parsing functions, as they have become very large. Maybe this should be refactored before doing anything else in the future. Thanks to regression tests, this should be fairly easy to do.

There are also a bunch of static function which may be better expressed as member functions.

I also personally like to see public stuff at the top of files and private stuff at the bottom or hidden in other files, so I don't have to go through all the code to find the public interfaces.

This isn't really standardised in Rust, so it's just a matter of preference...

**Comment by unlessgames** [comment]
* Moved the parsing into CycleParser and split the big parse function into parts
* Refactored some of the parsing with code reuse and additional readablity improvements.
* Applied autoformat and moved every pub to the top of the file.
* Removed the newly implemented features from the missing list in cycle.lua

Which functions do you think should be member functions? For me it feels better to have inputs be explicit but I get that using `self` is idiomatic to Rust, but I'm unsure what you refer to specifically.

**Comment by emuell** [comment]
That's great. A lot easier to read and consume now.

Let's merge this now, if you are happy with it?

---

Some more input/ideas for possible future refactoring: 

Constructor alike functions are always the first ones in Rust. In general, I think it makes sense to list function in the order they are intended to use.  That makes reading interfaces a lot easier too. 

```
impl Cycle {
    // create a new instance
    pub fn from(input: &str, seed: Option<[u8; 32]>) -> Result<Self, String>;
    // query some properties from it
    pub fn is_stateful(&self) -> bool;
    // use it
    pub fn generate(&mut self) -> Vec<Vec<Event>>;
    pub fn reset(&mut self);
}```

The whole thing is big enough to split it into a module. e.g.

```
tidal/
  cycle.rs
  cycle.pest
  cycle/
    parser.rs
    step.rs
    ...
  tests.rs
```

At some point, it actually might make sense to make this a separate crate and move it to crates.io? 

This is basically your project now anyway, this would give you proper credit, and it also might be useful in other projects as well. 

This also kinda requires writing docs for it and stuff. Rust's documentation system is excellent, but It's still a lot of work to create and maintain. See for example `cargo doc --open` for the project.

**Comment by unlessgames** [comment]
Reordered the Cycle impl, I'll split into files later. Let's merge it then!

> At some point, it actually might make sense to make this a separate crate and move it to crates.io?
>
> This is basically your project now anyway, this would give you proper credit, and it also might be useful in other projects as well.

Thanks! I suppose that does make sense. However, this would need its own implementation of the bjorklund and the '"patterns on the right hand side" feature before that.

> This also kinda requires writing docs for it and stuff. Rust's documentation system is excellent, but It's still a lot of work to create and maintain. See for example cargo doc --open for the project.

I was planning to make a doc pass once all features are implemented either way.

**Comment by emuell** [comment]
> Reordered the Cycle impl, I'll split into files later. 

Yes, please. This was meant as an idea for *future* refactorings anyway and let's keep the PRs on topic and smaller in future please.

**Pull request merged**
