### PR TITLE
Perf/rhythm seeking

### PR DESCRIPTION
**Pull request by emuell**
Speed up rhythm/phrase seeking. See https://github.com/emuell/afseq/issues/6

* when seeking phrases & rhythms batch process event iteration where possible
 
* try avoiding as much processing as possible while seeking, by using new "omit" event iter functions and cycle processing functions, which only maintain internal event iter state without actually computing events.

This is WIP, and already ~2x faster in many cases, but unfortunately still not fast enough. Ideal would be speedups of ~8x in normal processing vs seeking. When live editing phrase scripts, the seek function is called quite often for quite long periods of time (minutes up to hours). So this is very performance critical. 

@unlessgames As mentioned above, I've also added a new "omit" function to Cycle, but the implementation is rather ugly, but maybe still better than duplicating the whole "output" function for seeking. In general, anything that can be skipped should be skipped there - without breaking the internal state across cycle passes. To make this easier to check, I've added some tests for this, and also reorganised the tests to separate the seek tests from the others. 
See especially this change here:  https://github.com/emuell/afseq/commit/774fde627423af171b7329c1ac20eb2c757cc956

You may have some better ideas on how to fix or improve this.

PS: Omit is quite a shitty name for this, but unfortunately "skip" clashes with the standard Rust Iterator impls. I'll clean this skip vs seek vs omit wording after this PR is merged. This will change things across the whole repository. This PR already now is too big.

I'll now concentrate on optimising the other parts of the rhythms: generator patterns, emitters.

### CODE REVIEW

**Comment by emuell** [comment]
> See especially this change here: https://github.com/emuell/afseq/commit/774fde627423af171b7329c1ac20eb2c757cc956

I'm stupid and forgot the discussion we already had about this :) 

The only state that needs to be managed here is the random state of the cycle, which actually only is needed when the cycle is seeded. All other state is derived from the cycle's iteration count. So this commit can be removed. 

Instead, `omit` should always increase the cycle iteration count, and seeded cycles should derive the random number generator state from the cycle iteration count once on each new `generate` call.

**Comment by unlessgames** [comment]
The random output in the cycle currently has a regression in that it is no longer being deterministic based on the seed, since I've added the proper pattern mult and division. 

Seeding once per iteration will still not be deterministic enough if we want to mirror tidalcycles. Here is a quote from my previous comment on this

>`[[a b] | [c d]]/2`
>
>Here tidal will output a single event per cycle, but `b` will always follow `a` and `d` will always follow `c` since cycles are queried in whole and their randomness is a pure function of the iteration count of the (sub)cycle, the step and the seed.

I've added the `step` variable to the state (that you are removing here) to prepare for an eventual solution because it is no longer sufficient to have a starting seed as the multiply operator has to sample the subcycle it affects at arbitrary iterations to get the output.

So apart from a top level seed we would need the random generator to be sampled by position instead of just yielding some value when `gen_range` is called. Ideally we could be able to say `rng.sample(iteration + step)` where step is the absolute position index of the currently outputting step in the entire pattern or something similar. I might be missing something here but I think this would solve it.

**Comment by emuell** [comment]
The current behaviour is indeed still not correct (not behaving like the tidal reference implementation), but this is somewhat out of scope here. I would make this a follow-on TODO/PR, okay?

> Ideally we could be able to say rng.sample(iteration + step) where step is the absolute position index of the currently outputting step in the entire pattern or something similar.

With the introduction of `step`, the new `advance` function will actually have to use a function similar to `generate` to maintain the step, which will then depend on the random state. That's what confused me at first.

And If we're going to change that, it might be easier and more efficient to use a simpler PRNG, where the state index can be set directly, rather than having to reseed it every time. This should be possible with e.g. a simple Mersenne Twister.

**Comment by emuell** [comment]
@unlessgames okay for you to close and merge this? Then I can move on from here...

**Review by unlessgames — APPROVED** [review]

**Comment by unlessgames** [comment]
Sounds good! Maybe it will be best to implement this once the last feature for tidal is complete.

**Pull request merged**
