### PR TITLE
Tidal Cycle Rhythms

### PR DESCRIPTION
**Pull request by emuell**
- moved tidal parser out of rhythm into its own mod
- added a public interface to the cycle parser (export Cycle, Event, Pitch, Span, Target and Value)
- changed EventIter, to emit a vector of events instead of a single one
- added a new Cycle event iter impl which takes a cycle or mini string as input and emits a whole cycle for each new pulse

So for single pulse values in rhythms, whole cycles will be emitted. A single pulse duration defines the duration of the whole cycle then. I was unsure about this at first, but I really like it so far. It fits in with the existing rhythm handling and also allows you to use only a subset of the tidal mni specs, for example for note selection. 

Events are generated in batches of whole cycles. Event start times are applied using NoteEvent delays. This is a bit hacky and should probably only be a temporary solution. 

There's no mapping of string or float values to note events: floats and strings are simply skipped at the moment. This should be covered in a separate PR, as it's still unclear how exactly the mapping will work and look like in Lua.

There are no Lua bindings yet. This will be done next, as part of this PR. Until this is done, the attached player.rs example can be used to test things in Rust. 

[play.zip](https://github.com/emuell/afseq/files/15319505/play.zip)

@unlessgames I've only made minimal changes to the parser, but please verify.

### CODE REVIEW

**Comment by emuell** [comment]
Add basic Lua bindings now too:

Example:

```lua
return rhythm {
  unit = "bars",
  emit = cycle("[c5 [f5 f6]*2]]")
}
```

@unlessgames could you fill in the rough specs, TODOs here: 
https://github.com/emuell/afseq/blob/3ee11a23fe9bac000197e9c516cfe34f516e50c3/types/nerdo/library/cycle.lua#L16

I think you can do this better than me.

**Comment by unlessgames** [comment]
The code changes look fine to me!

Is there a simple way to run the example using cargo with ["jack" feature enabled for cpal](https://github.com/RustAudio/cpal?tab=readme-ov-file#feature-flags-for-audio-backends)? The default ALSA mode requires me to close all audio apps and kill my audio server.

**Comment by unlessgames** [comment]
If it's ok I've described the differences to Tidal instead of what is supported.

**Comment by emuell** [comment]
Thanks. Okay, let me merge this then and let's discuss everything else in new PRs and issues.

**Pull request merged**
